### PR TITLE
Change setup_raspberry_pi.md to use gdown instead of curl for google …

### PR DESCRIPTION
**Pull request by francisduvivier**
…drive download

Cookie acquisition with curl is not working anymore.

### CODE REVIEW

**Review by DocGarbanzo — COMMENTED** [review]
You are missing the definition of the environment variable CODE. That line needs to stay.

**Review by DocGarbanzo — COMMENTED** [review]
Actually I tried that download command and I got:
```bash
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?export=download&confirm=&id=1DCfoSwlsdX9X4E3pLClE1z0fvw8tFESP 
```
And pasting that command into the browser also failed. I think s/th is broken w/ the file on google drive. But I have already added an alternative download for the tf 2.2.0 binary in the doc - do you want to check that out?

**Comment by francisduvivier** [comment]
Hi there, thanks for checking, the drive link is indeed not correct like that. I'm away for the weekend but i'll get back after that.

**Comment by francisduvivier** [comment]
> ut I have already added an alternative download for the tf 2.2.0 binary in the doc - do you want to check that out?

Hi, that replacement is looking good and makes this PR obsolete, so I'll close this one.
I'll try and check out that wheel later.

**Comment by DocGarbanzo** [comment]
Thanks @francisduvivier for your help with identifying and fixing issues!

**Pull request closed without merging**
